dist: trusty
language: shell
sudo: yes

before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa -y
  - sudo apt-get update

install:
  - ./init.sh -install

script:
  - run/this.sh Lang 1

after_failure:
  - find
